configuración de entorno de desarrollo y conexión a la base de datos
ada-school/public-api-ada-school pull request #1
Opened 2024-01-09 14:55 UTC by ErikCasas

Creación del modelo to-do
Creación de git-hooks pre-push y pre-commit
Conexión a la base de datos de mongo usando una variable de entorno

2024-01-09 15:49 UTC, jgbernalp requested changes

2024-01-09 15:49 UTC, jgbernalp commented on server/common/db.ts
> +const dbName = process.env.DbName || 'api-ada';
es mejor poner todas estas variables dentro de un solo archivo. Por ejemplo `server/config.ts` con eso evitamos typos. Ademas las variables de entorno generalmente van todas en mayuscula. `DB_NAME` y `MONGO_URI`

2024-01-09 15:49 UTC, jgbernalp commented on server/common/server.ts
> +    app.use(bodyParser.json({ limit: process.env.REQUEST_LIMIT || '100kb' }));
Estas variables tambien deberian estar en el `server/config.ts`

2024-01-09 15:52 UTC, jgbernalp commented
@ErikCasas  No veo el modelo de TODO, en donde se creo? tampoco veo los scripts de pre commit o pre push, falto incluir algun commit?

2024-01-09 21:24 UTC, ErikCasas commented on server/common/db.ts
> +const dbName = process.env.DbName || 'api-ada';
Resuleto!

2024-01-10 06:24 UTC, jgbernalp approved these changes

2024-01-10 06:24 UTC, jgbernalp commented on server/common/swagger.ts
> +        app.enable('case sensitive routing');
Deberíamos remover esto ya que no es una buena práctica tener rutas que se comporten diferente teniendo el mismo nombre . Lo podía hacer en un nuevo PR

2024-01-10 06:24 UTC, merged