Todo api
ada-school/public-api-ada-school pull request #5
Opened 2024-01-16 14:41 UTC by ErikCasas

Se creó la nueva funcionalidad para solicitudes POST para la creación de nuevas ToDos
Se creó un middleware de validación de datos de entrada
Se creó una nueva interface customRequest
Se Tienen las bases para iniciar la creación de pruebas

2024-01-16 17:01 UTC, jgbernalp requested changes

2024-01-16 17:01 UTC, jgbernalp commented on package.json
> +  "module": "ESM",
es esto necesario?

2024-01-16 17:01 UTC, jgbernalp commented on server/todo-api/controllers/controller.ts
> +  async create(req: CustomRequest, res: Response, next:NextFunction):Promise<void> {
este `CustomRequest` ya estaba creado?

2024-01-16 17:01 UTC, jgbernalp commented on server/todo-api/controllers/controller.ts
> +export class Controller {
Creo que este controlador se deberia encargar tambien de la validacion. Para que la logica este centralizada aca. ver [MVC](https://es.wikipedia.org/wiki/Modelo%E2%80%93vista%E2%80%93controlador)

2024-01-16 21:58 UTC, ErikCasas commented on server/todo-api/controllers/controller.ts
> +export class Controller {
La lógica para validar la información está en el middleware de validateBodyRequest, creo que mantendría el principio MVC

2024-01-16 22:13 UTC, ErikCasas commented on server/todo-api/controllers/controller.ts
> +  async create(req: CustomRequest, res: Response, next:NextFunction):Promise<void> {
No, lo creé yo para poder añadir una propiedad todo, para pasar el nuevo todo ya estructurado y filtrado al controller

2024-01-16 22:13 UTC, ErikCasas commented on package.json
> +  "module": "ESM",
Ya se corrigió

2024-01-17 07:04 UTC, jgbernalp commented on server/todo-api/controllers/controller.ts
> +export class Controller {
Cual es el argumento de porque crees que mantendria la arquitectura? La responsabilidad del controlador debe ser también la validación de datos. Si esto se deja en un Middleware y el Middleware cambia o no se pone en la cadena de un request el sistema va a fallar. Es decir el controlador queda acoplado al Middleware. Es mejor que el controlador también maneje la validación con eso no hay acoplamiento.

2024-01-17 07:06 UTC, jgbernalp commented on server/todo-api/controllers/controller.ts
> +  async create(req: CustomRequest, res: Response, next:NextFunction):Promise<void> {
Aunque la lógica de validación debe estar también en el controlador. Siempre es bueno crear tipos específicos 👍

2024-01-18 08:24 UTC, jgbernalp requested changes

2024-01-18 08:24 UTC, jgbernalp commented on server/todo-api/controllers/controller.ts
> +        errorHandler(error, req, res, next);
no deberiamos llamar al error handler directamente, es mejor hacer throw del error y que el error handler se registre en el servidor para todos los errores

2024-01-18 08:24 UTC, jgbernalp commented on server/todo-api/controllers/controller.ts
> +      errorHandler(bodyErrors, req, res, next);
```suggestion
      throw bodyErrors
```

2024-01-18 08:24 UTC, jgbernalp commented on server/todo-api/controllers/controller.ts
> +    const isDateValid = (reqDate: Date): boolean => {
ya hay librerias que nos ayudan a validar para no reinventar la rueda, por ejemplo: https://www.npmjs.com/package/validator

2024-01-18 18:51 UTC, jgbernalp requested changes

2024-01-18 18:51 UTC, jgbernalp commented on server/todo-api/middlewares/error.handler.ts
> +
Este error handler deberia ser para todos los errores del servidor, pero lo podemos mover en otro PR

2024-01-18 18:51 UTC, jgbernalp commented on server/todo-api/types.d.ts
> +export interface CustomError extends Error {
```suggestion
export interface HTTPError extends Error {
```

2024-01-18 18:51 UTC, jgbernalp commented on test/index.test.ts
> +//iniciar conexión
```suggestion
```

2024-01-18 18:51 UTC, jgbernalp commented on test/jest.config.ts
> +  // coverageProvider: 'v8',
Por favor remover codigo que no se usa (dead code ☠️)
```suggestion
```

2024-01-18 18:57 UTC, ErikCasas commented on server/todo-api/middlewares/error.handler.ts
> +
Lo registré en server/common/server.ts en el método de routes, tengo entendido que desde ese punto queda registrado para atender todos los errores del servidor

2024-01-18 19:27 UTC, jgbernalp commented on server/todo-api/middlewares/error.handler.ts
> +
pero esta dentro de la carpeta `server/todo-api/middlewares/error.handler.ts` y no es un handler, ademas deberia estar en la carpeta del servidor ya que no es especifico del todo-api. La organizacion de los archivos es muy importante en los proyectos de software

2024-01-18 19:55 UTC, jgbernalp requested changes

2024-01-18 19:55 UTC, jgbernalp commented on package.json
> +    "start": "node dist/index.ts",
Esto es incorrecto. Node no corre TypeScript nativamente, porque estamos haciendo este cambio?

2024-01-18 19:55 UTC, jgbernalp commented on server/todo-api/controllers/controller.ts
> +import { CustomError } from '../types';
Custom error ya no existe. Se está validando TypeScript en VsCode?

2024-01-18 21:50 UTC, ErikCasas commented on package.json
> +    "start": "node dist/index.ts",
mi error, falta de atención al detalle

2024-01-18 21:52 UTC, ErikCasas commented on server/todo-api/controllers/controller.ts
> +import { CustomError } from '../types';
También fue mi error, TypeScript en VsCode está validando de forma correcta, realice los cambios desde el editor de github, por lo cual no se hicieron las validaciones, no lo volveré a hacer

2024-01-19 08:28 UTC, jgbernalp commented on server/todo-api/controllers/controller.ts
> +import { CustomError } from '../types';
No es recomendable hacer los cambios directo en GitHub porque perdemos todas las verificaciones automaticas, de types, linters, testing etc.

2024-01-19 14:38 UTC, jgbernalp requested changes

2024-01-19 14:38 UTC, jgbernalp commented on server/common/error.handler.ts
> +import l from './logger';
No es recomendable usar variables o imports de una sola letra, ya que es dificil de leer. Siempre debemos hacer el codigo para que sea legible para otras personas.
```suggestion
import log from './logger';
```

2024-01-19 14:38 UTC, jgbernalp commented on server/todo-api/controllers/controller.ts
> +        name: 'information in the body wrong',
```suggestion
        name: 'Bad request',
```

2024-01-19 14:38 UTC, jgbernalp commented on server/todo-api/types.d.ts
> +  errors?: { message: string }[];
es mejor usar la sintaxis de generics en Typescript, ya que es mas clara
```suggestion
  errors?: Array<{ message: string }>;
```

2024-01-19 14:38 UTC, jgbernalp commented on test/helper/mongoDbMemoryTestHelper.ts
> +export const conectionDbMemory = async (): Promise<void> => {
```suggestion
export const connectMemoryDB = async (): Promise<void> => {
```

2024-01-19 14:38 UTC, jgbernalp commented on test/helper/mongoDbMemoryTestHelper.ts
> +export const closeConectionDbMemory = async (): Promise<void> => {
```suggestion
export const closeMemoryDBConection = async (): Promise<void> => {
```

2024-01-22 18:14 UTC, jgbernalp requested changes

2024-01-22 18:14 UTC, jgbernalp commented on server/todo-api/controllers/controller.ts
> +      req.body as ToDoModel;
No es correcto hacer un cast directamente sin haber verificado antes que los atributos sean correctos. Debemos crear un [typeGuard](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) y verificar que los atributos esten dentro del objeto.
```suggestion
      req.body;
```

2024-01-22 18:14 UTC, jgbernalp commented on test/index.test.ts
> +  it('POST method only accepts correct information', async () => {
las pruebas deben tambien probar que pasa cuando se envian datos erroneos

2024-01-25 17:24 UTC, jgbernalp requested changes

2024-01-25 17:24 UTC, jgbernalp commented on server/todo-api/controllers/controller.ts
> +    const isObjectId = (
no es necesario que estas funciones esten aca, pueden estar por fuera de la clase ya que no dependen de la instancia de una clase. De resto lo veo bien

2024-01-25 17:42 UTC, ErikCasas commented on server/todo-api/controllers/controller.ts
> +  return typeof isCompleted === 'boolean';
utilicé el tipo de dato [unknow](https://mariusschulz.com/blog/the-unknown-type-in-typescript) ya que puede que manden por el cuerpo de la solicitud lo que sea, pero se que si se usa any se pierde toda la gracia de typeScript, no encontré alguna solución alternativa que yo entendiera, pero encontré que el tipo unknow es el que salva para no usar any, unknow

Así que mi duda es sobre que tan correcto es esta práctica

2024-01-25 17:54 UTC, jgbernalp commented on server/todo-api/controllers/controller.ts
> +  return typeof isCompleted === 'boolean';
Es correcto. Se prefiere unknown a any. Además hay que revisar en la validación que no envíen valores falsy. Como vacío,null, undefined o 0

2024-01-25 18:33 UTC, merged