Task/jwt validation
ada-school/public-api-ada-school pull request #9
Opened 2024-02-05 14:23 UTC by ErikCasas

Se creó la función middleware para validación de tokens de JWT
Se adaptaron los test para enviar tokens en cada llamado

2024-02-06 01:56 UTC, ErikCasas commented on server/todo-api/controllers/controller.ts
> +      if (id && !isObjectId(id)) {
tengo la duda de si las validaciones relacionadas con la información que proviene del token en verdad son necesarias

2024-02-06 10:47 UTC, jgbernalp commented on server/todo-api/controllers/controller.ts
> +      if (id && !isObjectId(id)) {
porque no lo serian? cual es el argumento en contra o a favor?

2024-02-06 10:52 UTC, jgbernalp requested changes

2024-02-06 10:52 UTC, jgbernalp commented on server/common/middleware/authJWT.ts
> +const existAuthorization = (
no es necesario hacer un type guard en este caso ya que es un tipo simple, que es un string o undefined

2024-02-06 10:52 UTC, jgbernalp commented on server/common/middleware/authJWT.ts
> +    authError = {
es incorrecto hacer de esto una variable global, significa que cada vez que llamamos esta funcion pueden existir errores de la ejecucion anterior...

2024-02-07 03:40 UTC, ErikCasas commented on server/todo-api/controllers/controller.ts
> +      if (id && !isObjectId(id)) {
Creo yo que al ser información que proviene del token, se puede dar por hecho que es información valida, sin embargo, se que aunque sea información proveniente de un token no significa que sea la correcta, ya que se puede llegar a generar un token con información errónea, pero teniendo en cuenta que es el mismo token que se usa en la plataforma, creo yo que llegado el caso que se generen los tokens mal, sería algo que uno se enteraría por la falla desde otras funcionalidades, como iniciar sesión antes que desde los propios llamados a esta API

2024-02-12 03:32 UTC, closed without merging